name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements_dev.txt

      - name: Preprocess Data
        run: python -m src.data preprocess-data

      - name: Authenticate with Google Cloud
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        run: gcloud auth activate-service-account --key-file="${{ secrets.GCP_CREDENTIALS }}"

      - name: Download Test Data
        run: |
          mkdir -p data/raw
          gsutil cp -r gs://learningras/data/raw data/raw    

      - name: Run tests
        run: pytest tests --cov=src --cov-report=xml
